"""
Daily Standup Generator (Feature #91).
Reads the local git log and generates a daily standup report.

Supports:
- Git log analysis for the day/week
- Automatic commit grouping by type (feat, fix, docs, etc.)
- Markdown-formatted report output
- Today, yesterday, and custom date queries

Usage:
    DailyStandupPlugin.execute("today")
    DailyStandupPlugin.execute("yesterday")
    DailyStandupPlugin.execute("this week")
    DailyStandupPlugin.execute("2026-07-27 to 2026-07-28")
"""

import datetime
import os
import re
import subprocess
from typing import Optional

from src.core import setup_logger
from src.plugin import BasePlugin, PluginResult

logger = setup_logger("daily_standup")


def _run_git_log(since: str, until: str, repo_path: str = ".") -> str:
    """Run git log command and return output."""
    try:
        result = subprocess.run(
            ["git", "log", f"--since={since}", f"--until={until}",
             "--pretty=format:%h|%an|%ad|%s",
             "--date=short", "--no-merges"],
            capture_output=True, text=True, timeout=15,
            cwd=repo_path,
        )
        return result.stdout
    except subprocess.TimeoutExpired:
        logger.warning("git log timed out after 15s")
        return ""
    except FileNotFoundError:
        logger.warning("git not found on this system")
        return ""
    except Exception as e:
        logger.warning(f"git log failed: {e}")
        return ""


def _parse_commits(log_output: str) -> list[dict]:
    """Parse git log output into structured commit data."""
    commits = []
    for line in log_output.strip().split("\n"):
        if not line.strip():
            continue
        parts = line.split("|", 3)
        if len(parts) == 4:
            hash_val, author, date, message = parts
            commits.append({
                "hash": hash_val[:8],
                "author": author,
                "date": date,
                "message": message.strip(),
            })
    return commits


def _categorize_commit(message: str) -> tuple[str, str]:
    """Categorize a commit message by type and component.

    Returns:
        (category, emoji) tuple
    """
    msg_lower = message.lower()
    categories = [
        (r'^feat[(:]', "Features", "✨"),
        (r'^fix[(:]', "Bug Fixes", "🐛"),
        (r'^docs[(:]', "Documentation", "📝"),
        (r'^refactor[(:]', "Refactoring", "♻️"),
        (r'^test[(:]', "Tests", "✅"),
        (r'^chore[(:]', "Chores", "🔧"),
        (r'^perf[(:]', "Performance", "⚡"),
        (r'^style[(:]', "Style", "💄"),
        (r'^ci[(:]', "CI/CD", "👷"),
        (r'^build[(:]', "Build", "📦"),
    ]
    for pattern, category, emoji in categories:
        if re.search(pattern, msg_lower):
            return category, emoji
    return "Other", "🔹"


def _format_standup_report(
    commits: list[dict],
    period_name: str,
    author_filter: Optional[str] = None,
) -> str:
    """Format commits into a daily standup markdown report."""
    if not commits:
        return (
            f"## 📋 Daily Standup — {period_name}\n\n"
            f"_No commits found for this period._\n\n"
            f"💡 Make sure you're in a git repository and have commits "
            f"in the specified period."
        )

    # Filter by author if specified
    if author_filter:
        commits = [c for c in commits if author_filter.lower() in c["author"].lower()]

    # Group by category
    grouped: dict[str, list[dict]] = {}
    category_emojis: dict[str, str] = {}
    for commit in commits:
        cat, emoji = _categorize_commit(commit["message"])
        if cat not in grouped:
            grouped[cat] = []
            category_emojis[cat] = emoji
        grouped[cat].append(commit)

    # Count unique authors
    authors = set(c["author"] for c in commits)

    lines = [
        f"## 📋 Daily Standup Report",
        f"",
        f"**Period:** {period_name}",
        f"**Total commits:** {len(commits)}",
        f"**Contributors:** {len(authors)} ({', '.join(sorted(authors))})",
        f"",
    ]

    for category in ["Features", "Bug Fixes", "Refactoring", "Documentation",
                      "Performance", "Tests", "CI/CD", "Chores", "Style", "Build", "Other"]:
        if category in grouped:
            emoji = category_emojis.get(category, "🔹")
            lines.append(f"### {emoji} {category}")
            for commit in grouped[category]:
                lines.append(f"- `{commit['hash']}` {commit['message']} _{commit['author']}_")
            lines.append("")

    lines.append("---")
    lines.append(f"📊 Generated by Project Atlas • {datetime.date.today()}")
    return "\n".join(lines)


class DailyStandupPlugin(BasePlugin):
    """
    Generates daily standup reports from git commit history.

    Commands:
    - "today": Commits from today
    - "yesterday": Commits from yesterday
    - "this week": Commits from this week (Monday → today)
    - "this month": Commits from this month
    - "last N days": Commits from last N days
    - "<date1> to <date2>": Custom date range

    Examples:
        "today"
        "yesterday"
        "this week"
        "last 7 days"
        "2026-07-20 to 2026-07-27"
    """

    name = "daily_standup"
    description = "Tạo báo cáo Daily Standup từ Git commit log"

    def execute(self, input_str: str) -> PluginResult:
        """Generate a daily standup report."""
        text = input_str.strip().lower()
        today = datetime.date.today()

        # Parse date range
        if not text or text == "today":
            since = today.isoformat()
            until = (today + datetime.timedelta(days=1)).isoformat()
            period = "Today"
        elif text == "yesterday":
            yesterday = today - datetime.timedelta(days=1)
            since = yesterday.isoformat()
            until = today.isoformat()
            period = "Yesterday"
        elif text in ("this week", "week"):
            monday = today - datetime.timedelta(days=today.weekday())
            since = monday.isoformat()
            until = (today + datetime.timedelta(days=1)).isoformat()
            period = f"This Week ({monday} → {today})"
        elif text in ("this month", "month"):
            first = today.replace(day=1)
            since = first.isoformat()
            until = (today + datetime.timedelta(days=1)).isoformat()
            period = f"This Month ({first} → {today})"
        elif text.startswith("last ") and " days" in text:
            try:
                num = int(text.split()[1])
                since = (today - datetime.timedelta(days=num)).isoformat()
                until = (today + datetime.timedelta(days=1)).isoformat()
                period = f"Last {num} Days"
            except (ValueError, IndexError):
                return PluginResult(success=False, error="Invalid format. Use: 'last N days'")
        elif " to " in text:
            parts = text.split(" to ")
            try:
                since = parts[0].strip()
                until_raw = parts[1].strip()
                until_date = datetime.date.fromisoformat(until_raw)
                until = (until_date + datetime.timedelta(days=1)).isoformat()
                period = f"{since} → {until_raw}"
            except (ValueError, IndexError):
                return PluginResult(success=False, error="Invalid date format. Use: YYYY-MM-DD to YYYY-MM-DD")
        else:
            # Treat as unknown command
            return PluginResult(
                success=False,
                error=(
                    "Vui lòng nhập khoảng thời gian.\n\n"
                    "Ví dụ:\n"
                    "- `today` — Hôm nay\n"
                    "- `yesterday` — Hôm qua\n"
                    "- `this week` — Tuần này\n"
                    "- `this month` — Tháng này\n"
                    "- `last 7 days` — 7 ngày qua\n"
                    "- `2026-07-20 to 2026-07-27` — Khoảng tùy chỉnh"
                )
            )

        log_output = _run_git_log(since, until)
        commits = _parse_commits(log_output)
        report = _format_standup_report(commits, period)

        return PluginResult(success=True, output=report, data={"commits": commits, "period": period})
