"""
Research Paper Writer Agent (Feature #69).
Assists in writing research papers with proper structure and APA citations.

Provides:
- Paper outline generation from topic
- Section-by-section writing guidance
- APA citation formatting
- Abstract generation
- References section formatting

Usage:
    ResearchWriterPlugin.execute("Write a paper about machine learning")
    ResearchWriterPlugin.execute("outline: AI in Healthcare")
    ResearchWriterPlugin.execute("abstract: title=My Research, topic=...")
"""

import re
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

from src.core import setup_logger
from src.plugin import BasePlugin, PluginResult

logger = setup_logger("research_writer")


@dataclass
class PaperSection:
    """A section of a research paper."""
    heading: str = ""
    content: str = ""
    subsections: list["PaperSection"] = field(default_factory=list)


@dataclass
class ResearchPaper:
    """A complete research paper structure."""
    title: str = "Untitled Research"
    authors: list[str] = field(default_factory=list)
    abstract: str = ""
    keywords: list[str] = field(default_factory=list)
    sections: list[PaperSection] = field(default_factory=list)
    references: list[str] = field(default_factory=list)
    date: str = ""


# ── Standard Paper Structure Templates ──

_PAPER_TEMPLATES = {
    "research": {
        "sections": [
            "Introduction",
            "Literature Review",
            "Methodology",
            "Results",
            "Discussion",
            "Conclusion",
        ],
        "description": "Standard research paper (IMRaD variant)",
    },
    "survey": {
        "sections": [
            "Introduction",
            "Background & Motivation",
            "Taxonomy & Classification",
            "Key Approaches",
            "Comparative Analysis",
            "Open Challenges",
            "Conclusion",
        ],
        "description": "Survey / Literature review paper",
    },
    "case_study": {
        "sections": [
            "Introduction",
            "Background",
            "Case Description",
            "Analysis",
            "Findings",
            "Recommendations",
            "Conclusion",
        ],
        "description": "Case study paper",
    },
    "technical": {
        "sections": [
            "Introduction",
            "System Architecture",
            "Implementation",
            "Experiments",
            "Results",
            "Discussion",
            "Conclusion",
        ],
        "description": "Technical / Systems paper",
    },
}


def _format_apa_citation(authors: str, year: str, title: str, source: str) -> str:
    """Format a citation in APA style."""
    return f"{authors} ({year}). {title}. *{source}*."


def _generate_outline(topic: str, template: str = "research") -> ResearchPaper:
    """Generate a paper outline from a topic."""
    paper = ResearchPaper(
        title=topic,
        date=datetime.now().strftime("%Y-%m-%d"),
    )

    template_info = _PAPER_TEMPLATES.get(template, _PAPER_TEMPLATES["research"])
    for section_title in template_info["sections"]:
        paper.sections.append(PaperSection(heading=section_title))

    return paper


def _format_paper(paper: ResearchPaper) -> str:
    """Format a research paper as Markdown."""
    lines = [
        f"# {paper.title}",
        "",
    ]

    if paper.authors:
        lines.append(f"**Authors:** {', '.join(paper.authors)}")
    if paper.date:
        lines.append(f"**Date:** {paper.date}")
    lines.append("")

    # Abstract
    if paper.abstract:
        lines.extend(["## Abstract", "", paper.abstract, ""])

    # Keywords
    if paper.keywords:
        lines.append(f"**Keywords:** {', '.join(paper.keywords)}")
        lines.append("")

    # Sections
    for i, section in enumerate(paper.sections, 1):
        lines.extend([f"## {i}. {section.heading}", ""])
        if section.content:
            lines.append(section.content)
            lines.append("")
        for j, sub in enumerate(section.subsections, 1):
            lines.extend([f"### {i}.{j}. {sub.heading}", ""])
            if sub.content:
                lines.append(sub.content)
                lines.append("")

    # References
    if paper.references:
        lines.extend(["## References", ""])
        for ref in paper.references:
            lines.append(f"- {ref}")
        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by Project Atlas • {paper.date}*")

    return "\n".join(lines)


class ResearchWriterPlugin(BasePlugin):
    """
    Assists in writing research papers with structured outlines and formatting.

    Commands:
    - `outline: <topic>` — Generate a paper outline
    - `abstract: <text>` — Format an abstract
    - `cite: <authors> <year> <title> <source>` — Format APA citation
    - `<topic>` — Generate full paper template

    Templates:
    - `research` — Standard IMRaD paper (default)
    - `survey` — Literature survey/review
    - `case_study` — Case study paper
    - `technical` — Technical/systems paper

    Examples:
        "Machine Learning in Healthcare"
        "outline: Quantum Computing survey"
        "cite: Smith, J. 2024 AI Advances Journal of AI"
        "abstract: This paper explores the applications of deep learning..."
    """

    name = "research_writer"
    description = "Hỗ trợ viết bài nghiên cứu khoa học với APA citations"

    def execute(self, input_str: str) -> PluginResult:
        """Generate research paper content."""
        text = input_str.strip()
        if not text:
            return PluginResult(
                success=False,
                error=(
                    "Vui lòng nhập chủ đề hoặc lệnh.\\n\\n"
                    "Lệnh:\\n"
                    "- `outline: <topic>` — Generate outline\\n"
                    "- `abstract: <text>` — Format abstract\\n"
                    '- `cite: <author> <year> <title> <journal>` — APA citation\\n'
                    "- `<topic>` — Full paper template\\n\\n"
                    "Ví dụ: `Machine Learning in Healthcare`"
                )
            )

        try:
            # Check for commands
            if text.lower().startswith("outline"):
                body = text[7:].strip(": ")
                parts = body.rsplit(" ", 1)
                template = "research"
                if len(parts) > 1 and parts[-1].lower() in _PAPER_TEMPLATES:
                    template = parts[-1].lower()
                    topic = parts[0]
                else:
                    topic = body

                paper = _generate_outline(topic, template)
                output = _format_paper(paper)
                return PluginResult(
                    success=True,
                    output=output,
                    data={"topic": topic, "template": template},
                )

            elif text.lower().startswith("abstract"):
                abstract_text = text[8:].strip(": ")
                lines = [
                    "## Abstract",
                    "",
                    abstract_text,
                    "",
                    "---",
                    "*Generated by Project Atlas*",
                ]
                return PluginResult(
                    success=True,
                    output="\n".join(lines),
                    data={"abstract": abstract_text},
                )

            elif text.lower().startswith("cite"):
                # Parse cite command using year detection
                cite_body = text[4:].strip()
                year_m = re.search(r'(\d{4})\s', cite_body)
                if year_m:
                    authors = cite_body[:year_m.start()].strip()
                    year = year_m.group(1)
                    rest = cite_body[year_m.end():].strip()
                    title, source = rest.rsplit(' ', 1) if ' ' in rest else (rest, '(source)')
                    citation = _format_apa_citation(authors, year, title, source)
                    return PluginResult(
                        success=True,
                        output=f"## 📚 APA Citation\n\n{citation}",
                        data={"citation": citation},
                    )
                else:
                    return PluginResult(
                        success=False,
                        error=(
                            "Format: `cite: <authors> <year> <title> <source>`\n\n"
                            "Ví dụ: `cite: Smith, J. 2024 AI Advances Journal of AI`\n\n"
                            "Cần có năm (4 chữ số) trong câu lệnh."
                        )
                    )



            else:
                # Treat as paper topic
                # Detect template from text
                template = "research"
                for tname in _PAPER_TEMPLATES:
                    if tname in text.lower():
                        template = tname
                        break

                paper = _generate_outline(text, template)
                output = _format_paper(paper)
                return PluginResult(
                    success=True,
                    output=output,
                    data={"topic": text, "template": template},
                )

        except Exception as e:
            logger.error(f"Research paper generation failed: {e}")
            return PluginResult(
                success=False,
                error=f"Không thể tạo bài nghiên cứu: {e}"
            )
